# US Companies By Revenue

In [6]:
from bs4 import BeautifulSoup
import requests
import pandas as pd

In [9]:
url = f"https://en.wikipedia.org/wiki/List_of_largest_companies_in_the_United_States_by_revenue"

headers = {
    'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36'
}


response = requests.get(url, headers=headers)

soup = BeautifulSoup(response.text, 'html.parser')

In [51]:
table_header = [th.text.strip() for th in soup.find('tr').find_all('th')]

In [52]:
column_data = soup.find_all('tr')

In [53]:
rows = []
for tr in column_data[1:]:
    row_cells = [td.text.strip() for td in tr.find_all('td')]
    
    
    if len(row_cells) == len(table_header):
        rows.append(row_cells)

In [54]:
companies_rev_df = pd.DataFrame(rows, columns = table_header)

In [57]:
companies_rev_df[['City', 'State']] = companies_rev_df['Headquarters'].str.split(',', n=1, expand=True)

companies_rev_df['City'] = companies_rev_df['City'].str.strip()
companies_rev_df['State'] = companies_rev_df['State'].str.strip()

In [58]:
companies_rev_df.head()

,Rank,Name,Industry,Revenue (USD millions),Revenue growth,Employees,Headquarters,City,State
0,1,Walmart,Retail,"680,985",5.1%,"2,100,000","Bentonville, Arkansas",Bentonville,Arkansas
1,2,Amazon,Retail and cloud computing,"637,959",11.0%,"1,556,000","Seattle, Washington",Seattle,Washington
2,3,UnitedHealth Group,Healthcare,"400,278",7.7%,"400,000","Minnetonka, Minnesota",Minnetonka,Minnesota
3,4,Apple,Technology,"391,035",2.0%,"164,000","Cupertino, California",Cupertino,California
4,5,CVS Health,Healthcare,"372,809",4.2%,"259,500","Woonsocket, Rhode Island",Woonsocket,Rhode Island

In [78]:
companies_rev_df = companies_rev_df.drop(columns=['Headquarters'])

KeyError: "['Headquarters'] not found in axis"

In [60]:
companies_rev_df.to_csv('companies_by_revenue.csv', index=False)

## Pulling List of Largest Private Companies

In [79]:
# Get all companies in wikitables
all_companies = soup.find_all('table', {'class': 'wikitable'})

In [80]:
private_header = [th.text.strip() for th in all_companies[1].find('tr').find_all('th')]

In [81]:
private_rows  = []

for tr in all_companies[1].find_all('tr')[1:]: # skip the header row
    cell_rows = [td.text.strip() for td in tr.find_all('td')]
    if len(cell_rows) == len(private_header):
        private_rows.append(cell_rows)

In [82]:
private_companies_df = pd.DataFrame(private_rows, columns=private_header)

In [83]:
private_companies_df[['City', 'State']] = private_companies_df['Headquarters'].str.split(',', n=1, expand=True)

private_companies_df['City'] = private_companies_df['City'].str.strip()

private_companies_df['State'] = private_companies_df['State'].str.strip()

private_companies_df = private_companies_df.drop(columns=['Headquarters'])

In [84]:
# Load to csv
private_companies_df.to_csv('largest_private_comapnies.csv', index=False)

## List of Companies by Profit

In [87]:
# Get the headers of profitable companies from 2nd table

companies_by_profit_header = [th.text.strip() for th in all_companies[2].find_all('th')]

In [88]:
### pull all the rows on the 2nd table

profitable_companies = []

for tr in all_companies[2].find_all('tr')[1:]: # skip the header row
    row_cell = [td.text.strip() for td in tr.find_all('td')]
    if len(row_cell) == len(companies_by_profit_header):
        profitable_companies.append(row_cell)

In [89]:
# Create the Dataframe
profitable_companies_df = pd.DataFrame(profitable_companies, columns=companies_by_profit_header)

In [90]:
# Split Headquarters into City and State, then drop Headquarters

profitable_companies_df[['City', 'State']] = profitable_companies_df['Headquarters'].str.split(',', n=1, expand=True)
profitable_companies_df['City'] = profitable_companies_df['City'].str.strip()
profitable_companies_df['State'] = profitable_companies_df['State'].str.strip()

# Drop Headquarters
profitable_companies_df = profitable_companies_df.drop(columns=['Headquarters'])

In [94]:
# Save in csv

profitable_companies_df.to_csv('profitable_companies.csv', index=False)

In [95]:
profitable_companies_df.head()

,Rank,Name,Industry,Profits(USD millions),City,State
0,1,Alphabet,Technology and cloud computing,"100,118",Mountain View,California
1,2,Apple,Technology,"93,736",Cupertino,California
2,3,Berkshire Hathaway,Conglomerate,"88,995",Omaha,Nebraska
3,4,Microsoft,Technology and cloud computing,"88,136",Redmond,Washington
4,5,Nvidia,Technology,"72,880",Santa Clara,California